### ISSUE TITLE
Syntax error on install

### ISSUE THREAD

**Issue by denilen** [corpetty/py-etherscan-api#16]
bash-3.2$ python setup.py install
running install
running build
running build_py
running install_lib
byte-compiling /Library/Python/2.7/site-packages/etherscan/accounts.py to accounts.pyc
  File "/Library/Python/2.7/site-packages/etherscan/accounts.py", line 24
    def get_transaction_page(self, page=1, offset=10000, sort='asc', internal=False) **->** list:
                                                                                         ^
SyntaxError: invalid syntax

**Comment by taylorjdawson** [comment]
I am not sure if you have come to this conclusion or not already but the reason for the failed install is because you are using python 2.7. The use of the `->` annotation (from Python 3) makes this module incompatible with Python 2. However, there is an [alternative annotation syntax](http://python-future.org/func_annotations.html) that could be used but that would up to @corpetty if he would want those changes to be implemented.

**Comment by corpetty** [comment]
I have chosen to not be backwards compatible with python2.  I would recommend upgrading to python3 to use this package.  A pull request of a fork that is compatible is always welcome.

**Comment by denilen** [comment]
thx
