### ISSUE TITLE
Line length?

### ISSUE THREAD

**Issue by taylorjdawson** [corpetty/py-etherscan-api#37]
Flake8 tests for line length of < 80. Is that what we want to go with?

**Comment by AndreMiras** [comment]
For my projects, I personally like to keep the default/mainstream rather than having to justify exception.
So yes 80 is a bit painful at first, but once you're used to it.
But yes maybe the maintainer will feel it's too much for now to enforce this rule, since the PR will have a lot of changes. But I would rather skip/ignore it via `tox.ini` rather than allowing a custom number of lines.
What do you think?

**Comment by corpetty** [comment]
Let's keep it <80.  It's annoying but I'm a fan of consistency, and pretty much hate long lines.

**Comment by AndreMiras** [comment]
Great thanks for your feedback. @taylorjdawson you're picking it up or do you want me to come with that pull request? That one would surely make other PR conflict, so it should be merged the earlier the better.
